CREATE TABLE TEACHERS(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT               NOT NULL,
   ADDRESS  CHAR (25) ,
   SALARY   DECIMAL (18, 2), 
   PHONE INT ,
   SUBJECTS  CHAR (40)
   PRIMARY KEY (ID)
);